### ISSUE TITLE
Exception: Value cannot be null

### ISSUE THREAD

**Issue by JoshuaCarroll** [ArkansasRepeaterCouncil/website#32]
Error #538 1/16/2019 4:03:50 PM
URL: https://www.arkansasrepeatercouncil.org/update/default.aspx?id=81
QueryString: id=81

Message
Value cannot be null.
Parameter name: login

Source
Octokit

Stack Trace
  at Octokit.Ensure.ArgumentNotNullOrEmptyString(String value, String name)
  at Octokit.Credentials..ctor(String login, String password, AuthenticationType authenticationType)
  at Octokit.Credentials..ctor(String login, String password)
  at Issue.Submit() in...
1/16/2019 4:03:50 PM - Exception of type 'System.Web.HttpUnhandledException' was thrown.
Error #539 1/16/2019 4:03:50 PM
URL: https://www.arkansasrepeatercouncil.org/update/default.aspx?id=81
QueryString: id=81

Message
Exception of type 'System.Web.HttpUnhandledException' was thrown.

Source
System.Web

Stack Trace
  at System.Web.UI.Page.HandleError(Exception e)
  at System.Web.UI.Page.ProcessRequestMain(Boolean includeStagesBeforeAsyncPoint, Boolean includeStagesAfterAsyncPoint)
  at System.Web.UI.Page.ProcessRequest(Boolean includeStagesBeforeAsyncPoint, Boolean...

**Comment by JoshuaCarroll** [comment]
Octokit is expecting data that isn't provided.  Upload the web.config file ya big dufus.

**Comment by JoshuaCarroll** [comment]
Done.
